name: Release
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
    contents: write
    packages: write

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     # build and publish in parallel: linux/amd64, linux/arm64, windows/amd64, darwin/amd64, darwin/arm64
    #     goos: [linux, windows, darwin]
    #     goarch: [amd64, arm64]
    #     exclude:
    #       - goarch: "386"
    #         goos: darwin
    #       - goarch: arm64
    #         goos: windows
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        # goos: ${{ matrix.goos }}
        # goarch: ${{ matrix.goarch }}
        # goversion: "https://dl.google.com/go/go1.13.1.linux-amd64.tar.gz"
        # project_path: "./cmd/commonmeta"
        # binary_name: "commonmeta"
        # extra_files: LICENSE README.md
